[build]
  publish = "build"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_BACKEND_URL = "https://your-backend-url.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "yarn start"
  port = 3000
  publish = "build"

