# Root Netlify configuration for KHLP frontend

[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_BACKEND_URL = "https://khlp-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


